"""The Version 0.3 result tables are generated from saved reports (synthetic reports here)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from baseline_tables import build_tables  # noqa: E402

MODELS = ("prevalence", "random_forest")
EXPERIMENTS = ("random", "within_year", "random_size_matched")


def ci(value: float) -> dict[str, float]:
    return {"estimate": value, "low": value - 0.05, "high": value + 0.05}


def write_reports(folder: Path) -> None:
    folder.mkdir(parents=True)
    (folder / "best_model_card.json").write_text(json.dumps(
        {"seed": 42, "model": "random_forest", "split": {"experiment": "random"}}), encoding="utf-8")
    pd.DataFrame([{"experiment": "random", "model": m, "seed": 42, "n": 426, "n_resistant": 97,
                   "roc_auc": 0.5 if m == "prevalence" else 0.749, "pr_auc": 0.228, "threshold": 1.32e-05,
                   "sensitivity": 0.907, "specificity": 0.392} for m in MODELS]
                 ).to_csv(folder / "validation_metrics.csv", index=False)
    pd.DataFrame([{"experiment": e, "model": m, "seed": 42, "train_size": 2977 if e == "random" else 1284,
                   "n": 856, "n_resistant": 197, "prevalence": 197 / 856, "roc_auc": 0.726, "pr_auc": 0.502,
                   "precision": 0.298, "f1": 0.44, "accuracy": 0.507, "brier": 0.155,
                   "calibration_slope": float("nan") if m == "prevalence" else 1.799,
                   "tp": 166, "fp": 391, "tn": 268, "fn": 31} for e in EXPERIMENTS for m in MODELS]
                 ).to_csv(folder / "test_metrics.csv", index=False)
    intervals = {e: {"used": 2000,
                     "intervals": {m: {k: ci(0.726) for k in ("roc_auc", "pr_auc", "sensitivity", "specificity")}
                                   for m in MODELS},
                     "differences_to_reference": {"prevalence": {"roc_auc": ci(0.226)}}} for e in EXPERIMENTS}
    (folder / "test_intervals.json").write_text(json.dumps(intervals), encoding="utf-8")
    pd.DataFrame([{"model": m, "roc_auc_difference": 0.013, "roc_auc_difference_low": -0.1,
                   "roc_auc_difference_high": 0.13} for m in MODELS]).to_csv(folder / "patient_overlap_check.csv",
                                                                            index=False)
    row = {"experiment": "random", "model": "random_forest", "seeds": 5}
    for metric in ("roc_auc", "pr_auc", "sensitivity", "specificity"):
        row.update({f"{metric}_mean": 0.727, f"{metric}_min": 0.725, f"{metric}_max": 0.729})
    pd.DataFrame([row]).to_csv(folder / "seed_variation.csv", index=False)
    step = {"median": 51.09, "p95": 70.77, "max": 157.07}
    (folder / "inference_timing.json").write_text(json.dumps(
        {"samples": 200, "single_spectrum_threads": 1, "batch_size": 426, "batch_inference_ms_per_sample": 0.82,
         "matches_stored_features": True, "preprocessing_ms": step, "inference_ms": step, "total_ms": step}),
        encoding="utf-8")


def test_tables_are_built_from_the_saved_reports(tmp_path):
    folder = tmp_path / "ecoli"
    write_reports(folder)
    text = build_tables(folder, "results/metrics/v0.3/ecoli")
    assert text.startswith("<!-- generated by scripts/baseline_tables.py from results/metrics/v0.3/ecoli -->")
    assert "| Random forest (saved) | 0.726 [0.676, 0.776] |" in text
    assert "1.32e-05" in text                                   # tiny cut-offs keep their digits
    assert "166 / 391 / 268 / 31" in text and "| – |" in text   # counts; undefined slope shown as a dash
    assert "| Prevalence only | +0.226 [+0.176, +0.276] |" in text
    assert "trained on 1284 samples" in text and "+0.013 [-0.100, +0.130]" in text
    assert "0.727 (0.725–0.729)" in text
    assert "| Read + preprocess | 51.09 | 70.77 | 157.07 |" in text
    assert "C:" not in text and str(tmp_path) not in text       # no local paths in the output
