"""The result tables are generated from saved reports (synthetic reports here), for either section."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from tuned_tables import SECTIONS, build_tables  # noqa: E402

MAIN = "random"
V04_NOTE = SECTIONS["tuning"]["note"]


def ci(value: float) -> dict[str, float]:
    return {"estimate": value, "low": value - 0.05, "high": value + 0.05}


def metrics_row(model: str, experiment: str = MAIN, **extra) -> dict[str, object]:
    row = {"experiment": experiment, "split": experiment, "model": model, "seed": 42, "calibrated": True,
           "setting": "{}", "train_size": 2977, "fit_seconds": 120.0, "predict_ms_per_sample": 0.5, "n": 856,
           "n_resistant": 197, "prevalence": 0.23, "threshold": 0.0123, "roc_auc": 0.75, "pr_auc": 0.55,
           "brier": 0.15, "accuracy": 0.52, "balanced_accuracy": 0.6, "sensitivity": 0.9, "recall": 0.9,
           "specificity": 0.3, "precision": 0.28, "f1": 0.43, "tp": 177, "fp": 461, "tn": 198, "fn": 20,
           "calibration_slope": 0.95, "calibration_intercept": 0.01}
    return {**row, **extra}


def write_reports(v04: Path, v03: Path) -> None:
    v04.mkdir(parents=True)
    v03.mkdir(parents=True)
    (v04 / "best_model_card.json").write_text(json.dumps(
        {"seed": 42, "model": "tuned_lightgbm", "model_kind": "lightgbm", "calibration": {"folds": 5},
         "split": {"experiment": MAIN}}), encoding="utf-8")
    pd.DataFrame([{"experiment": MAIN, "family": "lightgbm", "settings": 30, "best_setting": '{"n_estimators": 300}',
                   "cv_roc_auc_mean": 0.777, "cv_roc_auc_sd": 0.02, "cv_pr_auc_mean": 0.56,
                   "search_seconds": 2400.0},
                  {"experiment": MAIN, "family": "svm_rbf", "settings": 36, "best_setting": '{"C": 1.0}',
                   "cv_roc_auc_mean": 0.719, "cv_roc_auc_sd": 0.03, "cv_pr_auc_mean": 0.48,
                   "search_seconds": 5033.0}]).to_csv(v04 / "search_summary.csv", index=False)
    pd.DataFrame([metrics_row("tuned_lightgbm"), metrics_row("tuned_lightgbm", calibrated=False, brier=0.19),
                  metrics_row("v0.3_prevalence", roc_auc=0.5, calibration_slope=float("nan"))]
                 ).to_csv(v04 / "validation_metrics.csv", index=False)
    pd.DataFrame([metrics_row("tuned_lightgbm"), metrics_row("tuned_svm_rbf", roc_auc=0.70),
                  metrics_row("v0.3_random_forest", roc_auc=0.726, calibrated=False)]
                 ).to_csv(v04 / "test_metrics.csv", index=False)
    (v04 / "test_intervals.json").write_text(json.dumps({MAIN: {
        "used": 2000,
        "intervals": {m: {k: ci(v) for k in ("roc_auc", "pr_auc", "sensitivity", "specificity")}
                      for m, v in (("tuned_lightgbm", 0.75), ("tuned_svm_rbf", 0.70),
                                   ("v0.3_random_forest", 0.726))},
        "differences_to_reference": {"tuned_svm_rbf": {"roc_auc": ci(0.05)}},
        "differences_to_version_0_3": {"tuned_lightgbm": {"roc_auc": ci(0.024)}}}}), encoding="utf-8")
    step = {"median": 51.0, "p95": 70.0, "max": 157.0}
    for folder, total in ((v04, {"median": 60.0, "p95": 80.0, "max": 160.0}), (v03, step)):
        (folder / "inference_timing.json").write_text(json.dumps(
            {"samples": 200, "single_spectrum_threads": 1, "batch_size": 426, "batch_inference_ms_per_sample": 0.8,
             "matches_stored_features": True, "preprocessing_ms": step, "inference_ms": step,
             "total_ms": total}), encoding="utf-8")
    pd.DataFrame([{"comparison": "random_size_matched minus within_year", "model": "tuned_lightgbm",
                   "note": "same training size (the planned check)", "roc_auc_difference": 0.013,
                   "roc_auc_difference_low": -0.1, "roc_auc_difference_high": 0.13, "pr_auc_difference": 0.02,
                   "pr_auc_difference_low": -0.15, "pr_auc_difference_high": 0.19}]
                 ).to_csv(v04 / "patient_overlap_check.csv", index=False)
    row = {"experiment": MAIN, "model": "tuned_lightgbm", "seeds": 5}
    for metric in ("roc_auc", "pr_auc", "sensitivity", "specificity"):
        row.update({f"{metric}_mean": 0.75, f"{metric}_min": 0.74, f"{metric}_max": 0.76})
    pd.DataFrame([row]).to_csv(v04 / "seed_variation.csv", index=False)
    pd.DataFrame([metrics_row("prevalence", roc_auc=0.5, fit_seconds=0.02, predict_ms_per_sample=0.01),
                  metrics_row("random_forest", roc_auc=0.726, fit_seconds=13.8, predict_ms_per_sample=1.2)]
                 ).to_csv(v03 / "test_metrics.csv", index=False)


def test_tables_are_built_from_the_saved_reports(tmp_path):
    v04, v03 = tmp_path / "v0.4" / "ds", tmp_path / "v0.3" / "ds"
    write_reports(v04, v03)
    text = build_tables(v04, [("0.3", v03)], "0.4", V04_NOTE, "results/metrics/v0.4/ds")

    assert text.startswith("<!-- generated by scripts/tuned_tables.py from results/metrics/v0.4/ds -->")
    assert "| LightGBM | 30 | 0.777 ± 0.020 | 0.560 | 40 min |" in text          # search summary
    assert "| SVM (RBF) | 36 |" in text and "84 min" in text
    assert "| LightGBM (tuned) | yes | 0.750 |" in text                          # validation, calibrated
    assert "| LightGBM (tuned) | no |" in text                                   # and uncalibrated
    assert "0.0123" in text                                                      # small cut-offs keep digits
    assert "| LightGBM (tuned) (saved) | 0.750 [0.700, 0.800] |" in text         # test with intervals
    assert "+0.024 [-0.026, +0.074]" in text                                     # minus Version 0.3
    assert "| 0.3 | Prevalence only |" in text and "| 0.4 | LightGBM (tuned) |" in text   # comparison table
    assert "| 0.3 | Random forest |" in text and "13.8 s" in text and "40 min" in text
    assert "60.0 ms (Version 0.4)" in text and "51.0 ms (Version 0.3)" in text
    assert "+0.013 [-0.100, +0.130]" in text                                     # patient-overlap check
    assert "0.750 (0.740–0.760)" in text                                         # seed variation
    assert "| Read + preprocess | 51.0 | 70.0 | 157.0 |" in text
    assert "–" in text                                                           # missing values as a dash
    assert "C:\\" not in text and str(tmp_path) not in text                      # no local paths


def test_tables_work_without_the_optional_reports(tmp_path):
    v04, v03 = tmp_path / "v0.4" / "ds", tmp_path / "v0.3" / "ds"
    write_reports(v04, v03)
    (v04 / "patient_overlap_check.csv").unlink()
    (v04 / "seed_variation.csv").unlink()
    text = build_tables(v04, [("0.3", v03)], "0.4", V04_NOTE)
    assert "Patient-overlap check" not in text and "Seed variation" not in text
    assert "All models compared" in text


def test_a_third_version_is_compared_against_the_one_before_it(tmp_path):
    """Version 0.5: the networks are measured against Version 0.4, and all versions share one table."""
    v05, v04, v03 = tmp_path / "v0.5" / "ds", tmp_path / "v0.4" / "ds", tmp_path / "v0.3" / "ds"
    write_reports(v04, v03)
    write_reports(v05, tmp_path / "unused" / "ds")
    pd.DataFrame([metrics_row("tuned_mlp", roc_auc=0.71, fit_seconds=95.0),
                  metrics_row("v0.4_tuned_lightgbm", roc_auc=0.75, calibrated=False),
                  metrics_row("v0.3_prevalence", roc_auc=0.5)]).to_csv(v05 / "test_metrics.csv", index=False)
    (v05 / "best_model_card.json").write_text(json.dumps(
        {"seed": 42, "model": "tuned_mlp", "model_kind": "mlp", "calibration": {"folds": 5},
         "split": {"experiment": MAIN}}), encoding="utf-8")
    (v05 / "test_intervals.json").write_text(json.dumps({MAIN: {
        "used": 2000,
        "intervals": {m: {k: ci(v) for k in ("roc_auc", "pr_auc", "sensitivity", "specificity")}
                      for m, v in (("tuned_mlp", 0.71), ("v0.4_tuned_lightgbm", 0.75))},
        "differences_to_reference": {},
        "differences_to_reference_model": {"tuned_mlp": {"roc_auc": ci(-0.04)}}}}), encoding="utf-8")

    text = build_tables(v05, [("0.3", v03), ("0.4", v04)], "0.5", SECTIONS["deep"]["note"])
    assert "| 0.3 | Random forest |" in text and "| 0.4 | LightGBM (tuned) |" in text
    assert "| 0.5 | MLP (tuned) |" in text                     # every version in one table
    assert "| 0.4 | LightGBM (tuned) | 0.520 | 0.280 | 0.900 | 0.430 | 0.750 | 0.550 | 40 min |" in text
    assert "-0.040 [-0.090, +0.010]" in text                   # the network is behind Version 0.4, and says so
    assert "AUROC: this minus Version 0.4" in text
    assert "51.0 ms (Version 0.3), 60.0 ms (Version 0.4) and 60.0 ms (Version 0.5)" in text
