"""Markdown tables of the Version 0.3 results, generated from the saved reports (never typed by hand).

Run from the project root with the virtual environment active, after
`python scripts/train_baselines.py --evaluate-test`:

    python scripts/baseline_tables.py

Writes results/metrics/v0.3/<dataset>/tables.md and prints it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.tables import md_table, signed_ci, with_ci  # noqa: E402
from src.tables import model_name as name  # noqa: E402
from src.utils import ConfigError, load_config, project_path  # noqa: E402


def build_tables(report_dir: Path, label: str | None = None) -> str:
    """All tables as Markdown; `label` names the source folder in the header comment."""
    card = json.loads((report_dir / "best_model_card.json").read_text(encoding="utf-8"))
    seed, saved, main = card["seed"], card["model"], card["split"]["experiment"]
    validation = pd.read_csv(report_dir / "validation_metrics.csv")
    test = pd.read_csv(report_dir / "test_metrics.csv")
    intervals = json.loads((report_dir / "test_intervals.json").read_text(encoding="utf-8"))
    overlap = pd.read_csv(report_dir / "patient_overlap_check.csv")
    seeds = pd.read_csv(report_dir / "seed_variation.csv")
    timing = json.loads((report_dir / "inference_timing.json").read_text(encoding="utf-8"))
    val = validation[(validation["experiment"] == main) & (validation["seed"] == seed)]
    tst = test[(test["experiment"] == main) & (test["seed"] == seed)]
    ci = intervals[main]
    first = tst.iloc[0]
    out = [f"<!-- generated by scripts/baseline_tables.py from {label or report_dir.name} -->", ""]

    out += [f"**Validation, `{main}` split** (chooses the cut-off and the saved model; "
            f"{int(val.iloc[0]['n'])} samples, {int(val.iloc[0]['n_resistant'])} resistant)", ""]
    out.append(md_table([{"Model": name(r.model), "AUROC": f"{r.roc_auc:.3f}", "PR-AUC": f"{r.pr_auc:.3f}",
                          "Cut-off": f"{r.threshold:.3g}", "Sensitivity": f"{r.sensitivity:.3f}",
                          "Specificity": f"{r.specificity:.3f}"} for r in val.itertuples()]))

    out += ["", f"**Test, `{main}` split** ({int(first['n'])} samples, {int(first['n_resistant'])} resistant = "
            f"{first['prevalence']:.1%}; seed {seed}; 95 % intervals from {ci['used']} patient-level resamples)", ""]
    rows = []
    for r in tst.itertuples():
        i = ci["intervals"][r.model]
        rows.append({"Model": name(r.model) + (" (saved)" if r.model == saved else ""),
                     "AUROC": with_ci(i["roc_auc"]), "PR-AUC": with_ci(i["pr_auc"]),
                     "Sensitivity (= recall)": with_ci(i["sensitivity"]), "Specificity": with_ci(i["specificity"]),
                     "Precision": f"{r.precision:.3f}", "F1": f"{r.f1:.3f}", "Accuracy": f"{r.accuracy:.3f}",
                     "Brier": f"{r.brier:.3f}", "Calibration slope": "–" if pd.isna(r.calibration_slope)
                     else f"{r.calibration_slope:.2f}", "TP / FP / TN / FN": f"{r.tp} / {r.fp} / {r.tn} / {r.fn}"})
    out.append(md_table(rows))

    out += ["", f"**AUROC of the saved model ({name(saved)}) minus each other model**, same test samples "
            "(paired resamples):", ""]
    out.append(md_table([{"Compared with": name(m), "Difference [95 % interval]": signed_ci(d["roc_auc"])}
                         for m, d in ci["differences_to_reference"].items()]))

    matched = [e for e in intervals if e.endswith("_size_matched")]
    if matched:
        m_name = matched[0]
        w_name = next(e for e in intervals if e not in (main, m_name))
        out += ["", f"**Patient-overlap check** (test AUROC; `{m_name}` = `{main}` split trained on "
                f"{int(test[test['experiment'] == m_name]['train_size'].iloc[0])} samples from all years, "
                f"`{w_name}` = one year folder with complete patient groups, "
                f"{int(test[test['experiment'] == w_name]['train_size'].iloc[0])} training samples)", ""]
        rows = []
        for r in overlap.itertuples():
            rows.append({"Model": name(r.model),
                         f"{m_name}": with_ci(intervals[m_name]["intervals"][r.model]["roc_auc"]),
                         f"{w_name}": with_ci(intervals[w_name]["intervals"][r.model]["roc_auc"]),
                         "Difference [95 % interval]": f"{r.roc_auc_difference:+.3f} "
                                                       f"[{r.roc_auc_difference_low:+.3f}, "
                                                       f"{r.roc_auc_difference_high:+.3f}]"})
        out.append(md_table(rows))

    if len(seeds):
        out += ["", "**Seed variation** (stochastic models, test part; mean and range over "
                f"{int(seeds['seeds'].iloc[0])} seeds)", ""]
        out.append(md_table([{"Experiment": r.experiment, "Model": name(r.model),
                              "AUROC": f"{r.roc_auc_mean:.3f} ({r.roc_auc_min:.3f}–{r.roc_auc_max:.3f})",
                              "PR-AUC": f"{r.pr_auc_mean:.3f} ({r.pr_auc_min:.3f}–{r.pr_auc_max:.3f})",
                              "Sensitivity": f"{r.sensitivity_mean:.3f} ({r.sensitivity_min:.3f}–"
                                             f"{r.sensitivity_max:.3f})",
                              "Specificity": f"{r.specificity_mean:.3f} ({r.specificity_min:.3f}–"
                                             f"{r.specificity_max:.3f})"} for r in seeds.itertuples()]))

    out += ["", f"**Prediction time** of the saved model, {timing['samples']} validation spectra read from raw files, "
            f"{timing['single_spectrum_threads']} thread (milliseconds)", ""]
    out.append(md_table([{"Step": step, "Median": timing[key]["median"], "95th percentile": timing[key]["p95"],
                          "Maximum": timing[key]["max"]}
                         for step, key in (("Read + preprocess", "preprocessing_ms"),
                                           ("Model", "inference_ms"), ("Total", "total_ms"))]))
    out += ["", f"Batch of {timing['batch_size']} spectra with all CPU threads: "
            f"{timing['batch_inference_ms_per_sample']} ms per spectrum (model step only). "
            f"File-based predictions match the stored features: {timing['matches_stored_features']}.", ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description="Markdown tables of the Version 0.3 results.")
    parser.add_argument("--dataset", default=None)
    parser.add_argument("--config", type=Path, default=None)
    args = parser.parse_args()
    try:
        config = load_config(args.config)
    except ConfigError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    relative = f"results/metrics/v0.3/{args.dataset or config['dataset']['name']}"
    report_dir = project_path(relative)
    if not (report_dir / "test_metrics.csv").is_file():
        print(f"Error: no test results in {relative}; run scripts/train_baselines.py --evaluate-test first.",
              file=sys.stderr)
        return 1
    text = build_tables(report_dir, relative)
    (report_dir / "tables.md").write_text(text, encoding="utf-8")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
