"""Trace every number in the thesis chapter's Version 2.0 section back to the research report (Appendix A, part 2).

    python scripts/trace_thesis_numbers.py            # print part 2 of Appendix A
    python scripts/trace_thesis_numbers.py --check    # exit 1 if any number does not appear in the report

The rule is part 1's ("Generated mechanically"). Each number in the chapter's section 11 is listed with the report
sections where it occurs verbatim.

Left out, because they are not results:
- headings, and section, appendix and amendment labels;
- citation brackets, dates, version strings and file names.

A number with a sign is matched with its sign.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAPTER = ROOT / "docs" / "manuscript" / "thesis_chapter_v0.1-v1.4.md"
REPORT = ROOT / "docs" / "research_report_v0.1-v1.4.md"
SECTION = "## 11. Addendum: Version 2.0, external validation on MARISMa"
NUMBER = re.compile(r"(?<![\w.,])[+−]?\d[\d,]*(?:\.\d+)?(?![\w])")
NOT_RESULTS = [r"`[^`]*`", r"\]\([^)]*\)", r"\[\d+(?:, \d+)*\]", r"\d{4}-\d{2}-\d{2}", r"\b\d+\.\d+\.\d+\b",
               r"Version \d+(?:\.\d+)?", r"[Ss]ections? \d+(?:–\d+)?", r"Appendix A, part \d", r"amendment \d+",
               r"section \d+"]


def section_text(chapter: str) -> str:
    start = chapter.index(SECTION)
    end = chapter.index("\n## ", start + len(SECTION))
    lines = [line for line in chapter[start:end].splitlines() if not line.startswith("#")]
    text = "\n".join(lines)
    for pattern in NOT_RESULTS:
        text = re.sub(pattern, " ", text)
    return text


def numbers(text: str) -> list[str]:
    seen: dict[str, None] = {}
    for match in NUMBER.finditer(text):
        seen.setdefault(match.group(0).rstrip(","), None)
    return list(seen)


def report_sections(report: str) -> list[tuple[int, str]]:
    return [(m.start(), m.group(1).strip()) for m in re.finditer(r"^#{2,4} (.+)$", report, re.M)]


def trace(chapter: str, report: str) -> list[tuple[str, int, list[str]]]:
    headings = report_sections(report)
    out = []
    for number in numbers(section_text(chapter)):
        pattern = re.compile(rf"(?<![\d.,]){re.escape(number)}(?!\d)")
        positions = [m.start() for m in pattern.finditer(report)]
        names: list[str] = []
        for pos in positions:
            name = next((h for p, h in reversed(headings) if p <= pos), "(before the first section)")
            if name not in names:
                names.append(name)
        out.append((number, len(positions), names))
    return out


def table(rows: list[tuple[str, int, list[str]]]) -> str:
    missing = sum(1 for _, count, _ in rows if count == 0)
    lines = ["## Part 2: section 11 (Version 2.0), added 2026-10-06", "",
             "Generated by `scripts/trace_thesis_numbers.py`, by part 1's rule, from the chapter's section 11 and the "
             "research report (its section 13 holds the Version 2.0 results).", "",
             f"Numbers traced: {len(rows)}. Not found in the report: {missing}.", "",
             "| Number | Occurrences in the report | Report sections (first three) |", "|---|---|---|"]
    lines += [f"| {n} | {c} | {'; '.join(s[:3])} |" for n, c, s in rows]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    rows = trace(CHAPTER.read_text(encoding="utf-8"), REPORT.read_text(encoding="utf-8"))
    if args.check:
        missing = [n for n, c, _ in rows if c == 0]
        print(f"{len(rows)} numbers traced; not found in the report: {missing}")
        return 1 if missing else 0
    sys.stdout.reconfigure(encoding="utf-8")
    print(table(rows), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
