"""Version 2.0, step 6 - the result tables, from committed aggregates only.

    python scripts/v20_tables.py            # write results/metrics/v2.0/tables.md
    python scripts/v20_tables.py --check    # compare with the committed file; write nothing

The plan's step 6 says the tables are generated by script (docs/v2.0_marisma_plan.md, "Order of work"). This script
**predicts nothing, reads no label and recalculates no analysis.** It formats four committed aggregate records:

- `results/metrics/v2.0/marisma_evaluation.json`, the report of the one-time evaluation (results commit `89e73e8`);
- that evaluation's two rows of `results/experiments/test_evaluations.csv`, for their confusion counts;
- `results/metrics/v2.0/step3_run2.json`, the accepted step 3 record: reader exclusions by year and instrument;
- `results/metrics/v2.0/coverage_matching.json`: the 2024 isolates matched to a susceptibility record, before and
  after the reader (counts only).

Its only arithmetic is on those aggregates: shares of counts, and counts implied by a rate of a count (the R/I
isolates in the zone are n_in_zone minus NPV x n_in_zone). A derived count must come out a whole number, every
confusion count must reproduce the report's rate, and the four records must agree with each other, or the script
stops without writing.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from pathlib import Path
from typing import Any

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.tables import md_table  # noqa: E402
from src.utils import get_logger, project_path  # noqa: E402

log = get_logger("v20_tables")

REPORT = "results/metrics/v2.0/marisma_evaluation.json"
LOG = "results/experiments/test_evaluations.csv"
RUN2 = "results/metrics/v2.0/step3_run2.json"
COVERAGE = "results/metrics/v2.0/coverage_matching.json"
OUT = "results/metrics/v2.0/tables.md"
INPUTS = (REPORT, LOG, RUN2, COVERAGE)

AMENDED_RULE = "every feature bin has acquired data, with the training spectra's acquisition settings"   # D2
CELL_2024 = "2024 MBT-WIN10"
EXPERIMENT, MODEL, SEED = "external__MARISMa-2024__saved_model", "v0.4_tuned_lightgbm", 42
ROWS = {"primary": ("marisma_ecoli_ciprofloxacin", "v2.0-external"),
        "i_excluded": ("marisma_ecoli_ciprofloxacin__intermediate-exclude", "v2.0-external-sensitivity")}
METRICS = (("roc_auc", "AUROC"), ("pr_auc", "PR-AUC"), ("sensitivity", "Sensitivity at the frozen cut-off"),
           ("specificity", "Specificity"), ("precision", "Precision"), ("brier", "Brier score"),
           ("calibration_intercept", "Calibration intercept"), ("calibration_slope", "Calibration slope"),
           ("zone_coverage", "Zone coverage"), ("zone_npv", "Zone NPV"))
DEGENERATE = ("degenerate: every resample gave the same value, so this interval shows no uncertainty; it does not "
              "establish certainty")
SUPERSCRIPT = str.maketrans("-0123456789", "⁻⁰¹²³⁴⁵⁶⁷⁸⁹")


class TableError(RuntimeError):
    """The committed records disagree with each other, or a derived count is not a whole number."""


# --- formatting --------------------------------------------------------------------------------------------------

def num(x: float, digits: int = 3) -> str:
    return f"{x:.{digits}f}".replace("-", "−")


def count(n: int) -> str:
    return f"{n:,}"


def share(part: int, whole: int) -> str:
    return f"{100 * part / whole:.2f} %"


def pvalue(p: float) -> str:
    if p >= 0.001:
        return f"{p:.3f}".rstrip("0").rstrip(".") if p == 1 else f"{p:.3f}"
    mantissa, exponent = f"{p:.1e}".split("e")
    return f"{mantissa} × 10{str(int(exponent)).translate(SUPERSCRIPT)}"


def interval(entry: dict[str, Any], digits: int = 3) -> str:
    if "low" not in entry:
        return f"not estimable ({entry.get('reason') or entry.get('status', '')})"
    text = f"[{num(entry['low'], digits)}, {num(entry['high'], digits)}]"
    return f"{text} ({DEGENERATE})" if entry["low"] == entry["high"] else text


def whole(value: float, what: str) -> int:
    """A count implied by a rate of a count: it must be a whole number."""
    rounded = round(value)
    if abs(value - rounded) > 1e-6:
        raise TableError(f"{what} is not a whole number: {value!r}")
    return int(rounded)


# --- inputs ------------------------------------------------------------------------------------------------------

def load_inputs(root: Path | None = None) -> dict[str, Any]:
    path = (lambda rel: root / rel) if root is not None else project_path
    frame = pd.read_csv(path(LOG))
    rows = {}
    for name, (dataset, stage) in ROWS.items():
        hit = frame[(frame["dataset"] == dataset) & (frame["stage"] == stage) & (frame["experiment"] == EXPERIMENT)
                    & (frame["model"] == MODEL) & (frame["seed"] == SEED)]
        if len(hit) != 1:
            raise TableError(f"expected exactly one production-log row for {dataset}, found {len(hit)}")
        rows[name] = {k: int(hit.iloc[0][k]) for k in ("n", "n_resistant", "tp", "fp", "tn", "fn")}
    # The digest of the committed (LF) content: a Windows working copy may hold CRLF (the run wrote the report there),
    # while the repository and every CI checkout hold LF (.gitattributes), so the bytes are normalised first.
    report_bytes = path(REPORT).read_bytes().replace(b"\r\n", b"\n")
    return {"report": json.loads(report_bytes), "report_sha256": hashlib.sha256(report_bytes).hexdigest(),
            "rows": rows, "run2": json.loads(path(RUN2).read_bytes()),
            "coverage": json.loads(path(COVERAGE).read_bytes())}


# --- consistency checks --------------------------------------------------------------------------------------------

def check_rates(name: str, pop: dict[str, Any], row: dict[str, int]) -> None:
    m = pop["metrics"]
    if (row["n"], row["n_resistant"]) != (pop["n"], pop["n_resistant"]):
        raise TableError(f"{name}: the log row's n / n_resistant differ from the report")
    for metric, num_, den in (("sensitivity", row["tp"], row["tp"] + row["fn"]),
                              ("specificity", row["tn"], row["tn"] + row["fp"]),
                              ("precision", row["tp"], row["tp"] + row["fp"])):
        if not math.isclose(num_ / den, m[metric]["estimate"], rel_tol=0, abs_tol=1e-12):
            raise TableError(f"{name}: the log row's confusion counts do not reproduce the report's {metric}")


def reader_cells(run2: dict[str, Any], coverage: dict[str, Any]) -> tuple[dict[str, Any], dict[str, int]]:
    cells = run2["by_year_and_instrument"]
    pause = run2["pause_check"]
    if sum(c["isolates"] for c in cells.values()) != pause["denominator"] or \
            sum(c["excluded"] for c in cells.values()) != pause["numerator"]:
        raise TableError("the year-and-instrument cells do not add up to the pause check")
    amended = coverage["rules"][AMENDED_RULE][CELL_2024]
    cell = cells[CELL_2024]
    if (amended["isolates"], amended["kept"], amended["matched_and_kept"]) != \
            (cell["isolates"], cell["kept"], cell["kept_and_matched_to_an_amr_record"]):
        raise TableError("the coverage-matching record and the accepted run 2 record disagree on the 2024 cell")
    return cells, amended


# --- tables --------------------------------------------------------------------------------------------------------

def reader_table(run2: dict[str, Any], coverage: dict[str, Any]) -> str:
    cells, amended = reader_cells(run2, coverage)
    pause = run2["pause_check"]
    rows = [{"Population": "**All *E. coli* isolates, 2018–2024** (the pause check of amendment A6.4)",
             "Isolates": count(pause["denominator"]), "Excluded by the reader": count(pause["numerator"]),
             "Share": share(pause["numerator"], pause["denominator"])}]
    for name, c in cells.items():
        rows.append({"Population": f"{name}", "Isolates": count(c["isolates"]),
                     "Excluded by the reader": count(c["excluded"]), "Share": share(c["excluded"], c["isolates"])})
    excluded_matched = amended["matched"] - amended["matched_and_kept"]
    unmatched = amended["isolates"] - amended["matched"]
    excluded_unmatched = (amended["isolates"] - amended["kept"]) - excluded_matched
    rows.append({"Population": "**2024 isolates matched to a susceptibility record** (the evaluation population's "
                               "source)",
                 "Isolates": count(amended["matched"]), "Excluded by the reader": count(excluded_matched),
                 "Share": share(excluded_matched, amended["matched"])})
    rows.append({"Population": "2024 isolates without a susceptibility record", "Isolates": count(unmatched),
                 "Excluded by the reader": count(excluded_unmatched), "Share": share(excluded_unmatched, unmatched)})
    return md_table(rows)


def reader_sentence(run2: dict[str, Any], coverage: dict[str, Any]) -> str:
    cells, amended = reader_cells(run2, coverage)
    pause, cell = run2["pause_check"], cells[CELL_2024]
    excluded_matched = amended["matched"] - amended["matched_and_kept"]
    return (f"The {share(pause['numerator'], pause['denominator'])} that triggered the aggregate pause is an all-years "
            f"figure ({count(pause['numerator'])} of {count(pause['denominator'])} isolates), dominated by the FLEX-PC "
            f"years 2018–2019. Within the 2024 year folder, the source of every scoring candidate, the amended reader "
            f"excluded {count(cell['excluded'])} of {count(cell['isolates'])} isolates "
            f"({share(cell['excluded'], cell['isolates'])}), and {count(excluded_matched)} of the "
            f"{count(amended['matched'])} matched to a susceptibility record "
            f"({share(excluded_matched, amended['matched'])}).")


def flow_table(report: dict[str, Any]) -> str:
    pops = report["populations"]
    primary, i_excl = pops["primary_analysis"], pops["i_excluded_analysis"]
    candidates, matched = pops["candidate_scoring_cohort"], pops["matched_to_an_amr_record"]
    non_missing, conflicting = pops["with_a_non_missing_interpretation"], pops["conflicting_interpretations"]
    by_value = primary["by_value"]
    if sum(by_value.values()) != primary["labelled"] or primary["labelled"] != non_missing - conflicting \
            or primary["excluded_other_values"]:
        raise TableError("the label counts do not reconcile")
    rows = [
        {"Step": "Scoring candidates: every prepared 2024 isolate, MBT-WIN10", "Isolates": count(candidates),
         "Not carried forward": ""},
        {"Step": "Matched to a susceptibility record", "Isolates": count(matched),
         "Not carried forward": f"{count(candidates - matched)} without a record"},
        {"Step": "With a non-missing ciprofloxacin interpretation", "Isolates": count(non_missing),
         "Not carried forward": f"{count(matched - non_missing)} matched isolates without one"},
        {"Step": "With one valid interpretation: S " + count(by_value["S"]) + ", I " + count(by_value["I"])
                 + ", R " + count(by_value["R"]), "Isolates": count(primary["labelled"]),
         "Not carried forward": f"{count(conflicting)} with conflicting interpretations; "
                                f"{count(len(primary['excluded_other_values']))} values other than S, I, R"},
        {"Step": "**Primary population** (I counted as resistant)", "Isolates": count(primary["labelled"]),
         "Not carried forward": f"{count(primary['resistant'])} resistant, {count(primary['susceptible'])} "
                                "susceptible"},
        {"Step": "**I-excluded population** (descriptive)", "Isolates": count(i_excl["labelled"]),
         "Not carried forward": f"{count(i_excl['resistant'])} resistant, {count(i_excl['susceptible'])} "
                                f"susceptible; {count(by_value['I'])} I excluded"},
    ]
    return md_table(rows)


def holm_table(report: dict[str, Any]) -> str:
    test, family = report["primary"]["primary"], report["holm_family"]
    rows = [{"Antibiotic": "Ciprofloxacin", "Status": f"{test['status']}, {test['reading']}",
             "Resistant / susceptible": f"{count(test['n_resistant'])} / {count(test['n_susceptible'])}",
             "Brunner–Munzel statistic": num(test["statistic"], 2), "One-sided p": pvalue(test["p_value"]),
             "Holm input": pvalue(family["holm_inputs"]["ciprofloxacin"]),
             "Holm-adjusted p": pvalue(family["adjusted"]["ciprofloxacin"]),
             "Rejected at nominal α " + str(family["nominal_alpha"]): "yes" if family["rejected"]["ciprofloxacin"]
             else "no"},
            {"Antibiotic": "Ceftriaxone", "Status": "unavailable: no interpretation in MARISMa (dropped at step 2)",
             "Resistant / susceptible": "–", "Brunner–Munzel statistic": "–", "One-sided p": "–",
             "Holm input": pvalue(family["holm_inputs"]["ceftriaxone"]),
             "Holm-adjusted p": pvalue(family["adjusted"]["ceftriaxone"]),
             "Rejected at nominal α " + str(family["nominal_alpha"]): "yes" if family["rejected"]["ceftriaxone"]
             else "no"}]
    return md_table(rows)


def flagged(pop: dict[str, Any]) -> dict[str, int]:
    """Counts at the frozen cut-off implied by the report's rates (each must be a whole number)."""
    m, n_r, n_s = pop["metrics"], pop["n_resistant"], pop["n_susceptible"]
    tp = whole(m["sensitivity"]["estimate"] * n_r, "flagged resistant isolates")
    tn = whole(m["specificity"]["estimate"] * n_s, "unflagged susceptible isolates")
    if not math.isclose(tp / (tp + n_s - tn), m["precision"]["estimate"], rel_tol=0, abs_tol=1e-12):
        raise TableError("the implied counts do not reproduce the report's precision")
    return {"tp": tp, "fp": n_s - tn, "flagged": tp + n_s - tn}


def reading(key: str, pop: dict[str, Any]) -> str:
    m = pop["metrics"]
    if key == "roc_auc":
        return "the primary endpoint's estimate" if "primary" in pop else ""
    if key == "pr_auc":
        return f"no-skill level {num(pop['pr_auc_no_skill'])} (this population's prevalence)"
    if key == "sensitivity":
        return (f"{count(flagged(pop)['tp'])} of {count(pop['n_resistant'])} resistant isolates flagged; against the "
                f"0.90 research target: {pop['sensitivity_against_target']}")
    if key == "specificity":
        return f"{count(flagged(pop)['fp'])} of {count(pop['n_susceptible'])} susceptible isolates flagged resistant"
    if key == "precision":
        f = flagged(pop)
        return f"{count(f['tp'])} of the {count(f['flagged'])} flagged isolates resistant"
    if key == "brier":
        return (f"reference {num(m['brier_base_rate']['estimate'])}: a constant prediction at this population's own "
                "observed prevalence, an evaluation-cohort reference computable only after outcome access")
    if key == "calibration_intercept":
        e = m[key]
        side = ("lies above 0: resistance was more frequent than predicted (under-prediction)" if e["low"] > 0 else
                "lies below 0: resistance was less frequent than predicted (over-prediction)" if e["high"] < 0 else
                "contains 0")
        return f"0 = ideal (slope fixed at 1); the interval {side}"
    if key == "calibration_slope":
        e = m[key]
        side = ("contains 1, which does not show that the probabilities are calibrated" if e["low"] <= 1 <= e["high"]
                else "lies above 1" if e["low"] > 1 else "lies below 1")
        return f"1 = ideal; the interval {side}"
    if key == "zone_coverage":
        return f"{count(pop['zone']['n_in_zone'])} isolates below the frozen lower edge {pop['zone_lower_edge']}"
    if key == "zone_npv":
        z = pop["zone"]
        return (f"point {z['point']}; interval {z['interval']}. Version 0.8's reading (decides): "
                f"\"{z['version_0_8_reading']}\"; Version 0.7's: \"{z['version_0_7_reading']}\"")
    return ""


def endpoint_table(pop: dict[str, Any]) -> str:
    rows = []
    for key, label in METRICS:
        entry = pop["metrics"][key]
        rows.append({"Endpoint": label, "Estimate": num(entry["estimate"]), "95 % interval": interval(entry),
                     "Reading": reading(key, pop)})
    return md_table(rows)


def zone_table(name: str, pop: dict[str, Any]) -> str:
    z, npv = pop["zone"], pop["metrics"]["zone_npv"]
    n = z["n_in_zone"]
    susceptible = whole(npv["estimate"] * n, f"{name}: susceptible isolates in the zone")
    table = md_table([{"Isolates in the zone": count(n), "Susceptible": count(susceptible),
                       "Resistant (R or I)": count(n - susceptible), "NPV": num(npv["estimate"]),
                       "95 % interval": interval(npv)}])
    if npv.get("low") is not None and npv["low"] == npv["high"]:
        table += (f"\n\n**The interval [{num(npv['low'])}, {num(npv['high'])}] is a degenerate bootstrap interval.** "
                  f"All {count(n)} isolates in this zone were {'susceptible' if n == susceptible else 'resistant'}, "
                  "so no resample can give another value. It does not establish certainty, and the literal readings "
                  f"above rest on {count(n)} isolates of a descriptive subgroup.")
    return table


def confusion_table(rows: dict[str, dict[str, int]]) -> str:
    out = []
    for name, label in (("primary", "Primary"), ("i_excluded", "I excluded")):
        r = rows[name]
        out.append({"Population": label, "Flagged resistant, resistant (TP)": count(r["tp"]),
                    "Flagged resistant, susceptible (FP)": count(r["fp"]),
                    "Not flagged, susceptible (TN)": count(r["tn"]), "Not flagged, resistant (FN)": count(r["fn"])})
    return md_table(out)


def render(inputs: dict[str, Any]) -> str:
    report, rows = inputs["report"], inputs["rows"]
    primary, family, gap = report["primary"], report["holm_family"], report["gap"]
    sens = report["sensitivity_analyses"]
    check_rates("primary", primary, rows["primary"])
    check_rates("I excluded", sens["i_excluded"], rows["i_excluded"])
    robust = primary["primary"]["linkage_robustness"]
    groups = sens["by_sample_source_group"]
    labels = {"clinical": "Clinical specimen type",
              "ambiguous": "Source unknown or ambiguous: the three named ambiguous categories (`EXUDADO RECTAL`, "
                           "`ASPIRADO TRAQUEAL`, `JUGO GASTRICO`) and the suppressed rare categories, amendment E"}
    lines = [
        "# Version 2.0: external validation of the frozen ciprofloxacin model on MARISMa — result tables",
        "",
        "Generated by `scripts/v20_tables.py` from committed aggregates only: it predicts nothing, reads no label and "
        "recalculates no analysis. Source report: `results/metrics/v2.0/marisma_evaluation.json`, SHA-256 of its "
        f"committed (LF) content `{inputs['report_sha256']}`, written {report['written_utc']} by the one-time run "
        "(authorised code commit "
        f"`{report['authorised_commit'][:7]}`, run at `{report['preflight']['git_commit']}`).",
        "",
        f"**Scope:** {report['scope']}.",
        "",
        "Intervals are descriptive: 2,000 stratified bootstrap resamples (resistant and susceptible isolates resampled "
        "separately), seed 42, isolate-level because MARISMa has no patient linkage. They are expected to be too "
        "narrow if isolates from one patient are correlated.",
        "",
        "## 1. Reader exclusions: which denominator",
        "",
        reader_sentence(inputs["run2"], inputs["coverage"]),
        "",
        reader_table(inputs["run2"], inputs["coverage"]),
        "",
        "## 2. From scoring candidates to the analysis populations",
        "",
        flow_table(report),
        "",
        "Both populations meet the minimums (at least 50 resistant and 50 susceptible), so the primary reading is "
        "confirmatory.",
        "",
        "## 3. The primary test and the fixed Holm family",
        "",
        holm_table(report),
        "",
        "The statistic is negative because resistant isolates tend to score higher (scipy's sign convention, plan "
        "amendment B2).",
        "",
        f"- **Ciprofloxacin:** \"{family['conclusions']['ciprofloxacin']}\"",
        f"- **Ceftriaxone:** {family['conclusions']['ceftriaxone']}.",
        f"- **Error control (amendment B3, verbatim):** \"{family['error_control']}\"",
        "",
        "## 4. Endpoints: primary population "
        f"({count(primary['n'])} isolates; {count(primary['n_resistant'])} resistant, "
        f"{count(primary['n_susceptible'])} susceptible; prevalence {num(primary['prevalence'])})",
        "",
        f"Frozen cut-off {primary['threshold']}; nothing was refitted, recalibrated or re-thresholded.",
        "",
        endpoint_table(primary),
        "",
        "Counts at the frozen cut-off, from the evaluation's two production-log rows:",
        "",
        confusion_table(rows),
        "",
        "## 5. The confident-susceptible zone (probability below "
        f"{primary['zone_lower_edge']})",
        "",
        zone_table("primary", primary),
        "",
        f"Note: {primary['zone']['note']}.",
        "",
        "## 6. The gap: internal AUROC minus MARISMa AUROC",
        "",
        md_table([{"Internal AUROC (856 spectra, 197 resistant; patient-group bootstrap)":
                   f"{num(gap['internal_auroc'])} [{num(gap['internal_interval'][0])}, "
                   f"{num(gap['internal_interval'][1])}]",
                   "MARISMa AUROC": num(gap["external_auroc"]),
                   "Gap": num(gap["gap"]), "95 % interval (unpaired second level)":
                   f"[{num(gap['low'])}, {num(gap['high'])}]",
                   "Demonstrated": "yes" if gap["demonstrated"] else "no"}]),
        "",
        f"Reading: {gap['reading']}. No equivalence or non-inferiority margin was pre-specified, so neither was "
        "tested.",
        "",
        "## 7. Linkage robustness (descriptive; amendment A3.7)",
        "",
        md_table([{"Design effect (assumed)": num(robust["design_effect"], 1),
                   "Statistic": num(robust["statistic"], 2), "Degrees of freedom": num(robust["df"], 1),
                   "One-sided p": pvalue(robust["p_value"])}]),
        "",
        "The doubled variance is an assumed design effect, not an estimate from MARISMa and not a correction for the "
        "unknown patient clustering. It changes no decision.",
        "",
        "## 8. Sensitivity analyses (descriptive; no p-value)",
        "",
        "### 8.1 I excluded "
        f"({count(sens['i_excluded']['n'])} isolates; {count(sens['i_excluded']['n_resistant'])} resistant, "
        f"{count(sens['i_excluded']['n_susceptible'])} susceptible)",
        "",
        endpoint_table(sens["i_excluded"]),
        "",
        zone_table("I excluded", sens["i_excluded"]),
        "",
    ]
    for key, group in groups.items():
        lines += [f"### 8.{2 + list(groups).index(key)} {labels.get(key, key)} "
                  f"({count(group['n'])} isolates; {count(group['n_resistant'])} resistant, "
                  f"{count(group['n_susceptible'])} susceptible)", "",
                  endpoint_table(group), "", zone_table(key, group), ""]
    lines += [
        f"- **All sources:** {sens['all_sources']}.",
        f"- **By period:** {sens['by_period']}.",
        "",
        "## 9. Availability of each registered analysis",
        "",
        md_table([{"Analysis": k, "Availability": v} for k, v in report["availability"].items()]),
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed tables; write nothing")
    args = parser.parse_args(argv)
    text = render(load_inputs())
    out = project_path(OUT)
    if args.check:
        current = out.read_bytes().replace(b"\r\n", b"\n").decode("utf-8") if out.exists() else ""
        if current != text:
            log.error("%s differs from what the committed records generate", OUT)
            return 1
        log.info("%s matches the committed records", OUT)
        return 0
    out.write_text(text, encoding="utf-8", newline="\n")
    log.info("wrote %s", OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
