"""Three reproducible synthetic MALDI-TOF spectra for the research demo (seed 42).

They are generated, not measured. No organism, isolate, patient or laboratory stands behind them, and none of them
has a susceptibility label: a model score on one of them says nothing about any organism. They exist to show the
pipeline's mechanics (reading, preprocessing, scoring) with the frozen model.

The three examples are the first three draws of this generator with seed 42. They were fixed, and committed, before
the model scored any of them, so they are not chosen by their scores.

Each spectrum imitates the shape of a linear MALDI-TOF acquisition: about 20,000 channels whose square-root m/z is
evenly spaced (time of flight), a decaying baseline, Gaussian peaks whose width grows with m/z, and counting noise.
The text layout is the one the project's reader accepts (`src/data_loader.read_raw_spectrum`): `#` comment lines, a
header line, then "m/z intensity" rows.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

SEED = 42
N_EXAMPLES = 3
N_POINTS = 20_000
MZ_FIRST, MZ_LAST = 1_960.0, 20_140.0
SYNTHETIC_MARK = "# SYNTHETIC: not a measured isolate"


@dataclass(frozen=True)
class Example:
    """One synthetic spectrum. It has an identifier and its points, and deliberately no label."""

    id: str
    title: str
    mz: np.ndarray
    intensity: np.ndarray

    @property
    def n_points(self) -> int:
        return int(self.mz.size)

    def to_text(self) -> str:
        """The spectrum as a raw text file in the layout the project's reader accepts."""
        number = self.id.rsplit("-", 1)[-1]
        lines = [SYNTHETIC_MARK,
                 f"# Generated by demo/synthetic.py with seed {SEED}: example {number} of {N_EXAMPLES}.",
                 "# No susceptibility label exists for it; its score demonstrates the pipeline only.",
                 "mass intensity"]
        lines += [f"{m:.4f} {int(y)}" for m, y in zip(self.mz, self.intensity, strict=True)]
        return "\n".join(lines) + "\n"


def mz_axis(n: int = N_POINTS) -> np.ndarray:
    """Channel m/z values: square-root m/z is linear in the channel index, as for a linear time-of-flight scan."""
    return np.linspace(np.sqrt(MZ_FIRST), np.sqrt(MZ_LAST), n) ** 2


def _draw(rng: np.random.Generator, mz: np.ndarray) -> np.ndarray:
    n_peaks = int(rng.integers(45, 76))
    centres = np.exp(rng.uniform(np.log(2_050.0), np.log(16_000.0), n_peaks))
    heights = rng.lognormal(mean=6.0, sigma=0.9, size=n_peaks)
    widths = centres / rng.uniform(500.0, 1_100.0, n_peaks)           # resolving power m/dm of 500-1,100
    peaks = (heights[:, None] * np.exp(-0.5 * ((mz[None, :] - centres[:, None]) / widths[:, None]) ** 2)).sum(0)
    baseline = rng.uniform(800.0, 1_600.0) * np.exp(-(mz - MZ_FIRST) / rng.uniform(1_500.0, 3_000.0)) + 40.0
    expected = baseline + peaks
    counts = expected + rng.normal(0.0, 1.0, mz.size) * np.sqrt(expected)   # counting noise
    return np.clip(np.round(counts), 0, None)


def generate(seed: int = SEED, n: int = N_EXAMPLES) -> list[Example]:
    """The first `n` draws of the generator: the demo uses seed 42 and n = 3, and nothing else."""
    rng = np.random.default_rng(seed)
    mz = mz_axis()
    return [Example(id=f"synthetic-{i}", title=f"Synthetic spectrum {i}", mz=mz, intensity=_draw(rng, mz))
            for i in range(1, n + 1)]


def plot_points(example: Example, buckets: int = 1_200) -> dict[str, list[float]]:
    """A light series for the browser plot: the maximum of each m/z bucket, so peaks stay visible."""
    edges = np.linspace(0, example.n_points, buckets + 1).astype(int)
    mz = [float(example.mz[a:b].mean()) for a, b in zip(edges[:-1], edges[1:], strict=True) if b > a]
    top = [float(example.intensity[a:b].max()) for a, b in zip(edges[:-1], edges[1:], strict=True) if b > a]
    return {"mz": [round(m, 2) for m in mz], "intensity": top}
